[package]
name = "rust_web_cgi"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
http = "0.2"
log = "0.4"
env_logger = "0.10.0"
strum = "0.25"
strum_macros = "0.25"

